#!/bin/bash
#SBATCH -J keys
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=3700
#SBATCH --gres=gpu:quadro_rtx_6000:1
#SBATCH --time=48:00:00

module purge
module load CUDA/11.8.0 GCCcore/13.2.0  Python/3.11.5
source ~/gschnet-env/bin/activate
python /home/chem/msummc/2192510_training_and_generation/scripts/trouble_shooting_erroe.py