name: DGM-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - ase=3.22.1
  - cycler=0.11.0
  - ipython=7.33.0
  - matplotlib=3.5.3
  - networkx=2.6.3
  - numpy=1.21.6
  - openbabel=2.4.1
  - pandas=1.3.5
  - rdkit=2022.09.1
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - tqdm=4.67.1
  - pip:
      #- ifg==2.2.3
      #- pybel==0.15.5
      - schnetpack==0.3
      - torch==1.13.1
