#!/bin/bash
#SBATCH -J gschnet
#SBATCH --partition=gpu-devel
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=3700
#SBATCH --gres=gpu:quadro_rtx_6000:1
#SBATCH --time=01:30:00
module purge
module load CUDA/11.8.0 GCCcore/13.2.0  Python/3.11.5
source ~/gschnet-env/bin/activate
HYDRA_FULL_ERROR=1 python /home/chem/msummc/gschnet/schnetpack-gschnet/src/scripts/generate.py --config-dir=/home/chem/msummc/gschnet/gschnet-configs  --config-name generate_molecules  'modeldir="/home/chem/msummc/2192510_training_and_generation/models/qm9_no_conditions/1085620_gpu004"' 'generate.n_molecules=20000' > gen.out