#!/bin/bash
#SBATCH -J gschnet
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=3700
#SBATCH --gres=gpu:quadro_rtx_6000:1
#SBATCH --time=00:30:00
module purge
module load CUDA/11.8.0 GCCcore/13.2.0  Python/3.11.5
source ~/gschnet-env/bin/activate
python /home/chem/msummc/gschnet/schnetpack-gschnet/src/scripts/train.py --config-dir=/home/chem/msummc/gschnet/gschnet-configs experiment=gschnet_qm9 
