#!/bin/bash
#SBATCH -J gschnet
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=3700
#SBATCH --gres=gpu:quadro_rtx_6000:1
#SBATCH --time=48:00:00
module purge
module load CUDA/11.8.0 GCCcore/13.2.0  Python/3.11.5
source ~/gschnet-env/bin/activate
python /home/chem/msummc/gschnet/schnetpack-gschnet/src/scripts/train.py --config-dir=/home/chem/msummc/gschnet/gschnet-configs experiment=gschnet_template.yaml data.datapath=/home/chem/msummc/GeoLDM_drug/GeoLDM/data/geom/geom_drugs_30.db data.batch_size=5 data.num_train=45000 data.num_val=4500 globals.name=custom_data globals.id=drugs_run_30 globals.model_cutoff=10 globals.prediction_cutoff=5 globals.placement_cutoff=2.6 globals.atom_types="[1,  5,  6,  7,  8,  9, 13, 14, 15, 16, 17, 33, 35, 53, 80, 83]" globals.draw_random_samples=5 data=custom_data_cached  globals.covalent_radius_factor=1.3 run.id=drugs_run_30
