run:
  work_dir: /gpfs/home/chem/msummc/2192510_training_and_generation
  data_dir: /gpfs/home/chem/msummc/2192510_training_and_generation/data
  path: /gpfs/home/chem/msummc/2192510_training_and_generation/models/custom_data
  experiment: default
  id: 1.3_2.6_run
  ckpt_path: checkpoints/last.ckpt
globals:
  model_path: best_model
  name: custom_data
  id: 1.3_2.6_run
  model_cutoff: 10
  prediction_cutoff: 5
  placement_cutoff: 2.6
  atom_types:
  - 1
  - 3
  - 5
  - 6
  - 7
  - 8
  - 9
  - 14
  - 15
  - 16
  - 17
  - 33
  - 34
  - 35
  - 52
  - 53
  use_covalent_radii: true
  covalent_radius_factor: 1.3
  origin_type: 121
  focus_type: 122
  stop_type: 123
  lr: 0.0001
  draw_random_samples: 5
  data_workdir: null
  cache_workdir: null
trainer:
  _target_: pytorch_lightning.Trainer
  devices: 1
  min_epochs: null
  max_epochs: 100000
  enable_model_summary: true
  profiler: null
  gradient_clip_val: 0
  accumulate_grad_batches: 1
  val_check_interval: 1.0
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 0
  fast_dev_run: false
  overfit_batches: 0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  detect_anomaly: false
  precision: 32
  accelerator: auto
  num_nodes: 1
  deterministic: false
  inference_mode: false
callbacks:
  model_checkpoint:
    _target_: schnetpack.train.ModelCheckpoint
    monitor: val_loss
    save_top_k: 1
    save_last: true
    mode: min
    verbose: false
    dirpath: checkpoints/
    filename: '{epoch:02d}'
    model_path: best_model
  early_stopping:
    _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: val_loss
    patience: 25
    mode: min
    min_delta: 0.0
    check_on_train_epoch_end: false
  lr_monitor:
    _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: epoch
  progress_bar:
    _target_: pytorch_lightning.callbacks.TQDMProgressBar
    refresh_rate: 100
  model_summary:
    _target_: pytorch_lightning.callbacks.ModelSummary
    max_depth: -1
task:
  optimizer_cls: torch.optim.AdamW
  optimizer_args:
    lr: 0.0001
    weight_decay: 0.0
  scheduler_cls: schnetpack.train.ReduceLROnPlateau
  scheduler_monitor: val_loss
  scheduler_args:
    mode: min
    factor: 0.5
    patience: 10
    threshold: 0.0
    threshold_mode: rel
    cooldown: 10
    min_lr: 1.0e-06
    smoothing_factor: 0.0
  _target_: schnetpack_gschnet.ConditionalGenerativeSchNetTask
model:
  _target_: schnetpack_gschnet.ConditionalGenerativeSchNet
  representation:
    _target_: schnetpack_gschnet.SchNet
    n_atom_basis: 128
    n_interactions: 9
    radial_basis:
      _target_: schnetpack.nn.radial.GaussianRBF
      n_rbf: 25
      cutoff: 10
    cutoff_fn:
      _target_: schnetpack.nn.cutoff.CosineCutoff
      cutoff: 10
    max_z: 130
  atom_types:
  - 1
  - 3
  - 5
  - 6
  - 7
  - 8
  - 9
  - 14
  - 15
  - 16
  - 17
  - 33
  - 34
  - 35
  - 52
  - 53
  origin_type: 121
  focus_type: 122
  stop_type: 123
  model_cutoff: 10
  prediction_cutoff: 5
  placement_cutoff: 2.6
  type_prediction_n_hidden:
  - 206
  - 156
  - 106
  - 56
  distance_prediction_n_hidden:
  - 264
  - 273
  - 282
  - 291
data:
  _target_: schnetpack_gschnet.data.GenerativeAtomsDataModule
  data_workdir: null
  placement_cutoff: 2.6
  use_covalent_radii: true
  covalent_radius_factor: 1.3
  num_workers: 8
  datapath: /home/chem/msummc/2192510_training_and_generation/Databases/OE62_full.db
  batch_size: 5
  num_train: 45000
  num_val: 4500
  transforms:
  - _target_: schnetpack.transform.SubtractCenterOfMass
  - _target_: schnetpack_gschnet.transform.OrderByDistanceToOrigin
  - _target_: schnetpack_gschnet.transform.ConditionalGSchNetNeighborList
    model_cutoff: 10
    prediction_cutoff: 5
    placement_cutoff: 2.6
    environment_provider: matscipy
    use_covalent_radii: true
    covalent_radius_factor: 1.3
  - _target_: schnetpack_gschnet.transform.BuildAtomsTrajectory
    centered: true
    origin_type: 121
    focus_type: 122
    stop_type: 123
    draw_random_samples: 5
    sort_idx_i: false
  - _target_: schnetpack.transform.CastTo32
logger:
  tensorboard:
    _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
    save_dir: tensorboard/
    name: default
print_config: true
